name: Build Cherry Kernel for cactus

on:
  push:
    paths:
    - 'cactus.trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        sudo apt install -y wget bc build-essential make autoconf automake
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
        tar -xJf gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
        mv gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf gcc
        rm gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.tar.xz
        ARCH=arm make O=out cactus_defconfig
        ARCH=arm CROSS_COMPILE=$(pwd)/gcc/bin/arm-none-linux-gnueabihf- make O=out -j$(nproc --all)
        git clone https://github.com/DevelopmentJunkyard/AnyKernel3 -b cactus ak3
        cp out/arch/arm/boot/zImage-dtb ak3
        cd ak3
        zip -r9 CherryKernel-9.2-cactus.zip *
        cp CherryKernel-9.2-cactus.zip ../

    - uses: actions/upload-artifact@v1
    with:
      name: CherryKernel-9.2-cactus
      path: CherryKernel-9.2-cactus.zip
